### PR TITLE
docs: Add quickstart steps for beginners

### PR DESCRIPTION
**Pull request by jknight**
- Adds step for newcomers to get running quickly

### CODE REVIEW

**Comment by hamza1311** [comment]
Just a thought: if I'm new to a project, I wouldn't want to `git clone` the repo just to try out a basic hello world example. I think the changes you made in this PR are better suited to be in `examples/README.md`

**Comment by jknight** [comment]
Actually, that is exactly what I did @hamza1311  - I am comparing Rust websocket frameworks and wanted to try a few out as quickly as possible. 
After a `git clone` of warp, it wasn't 100% clear to me (at least) how to get a quick "hello world" going to test -- `cargo run --example x` wasn't obvious.
But, yes, could be in examples/README.md. Happy to move it if you prefer ?

**Comment by hamza1311** [comment]
> it wasn't 100% clear to me (at least) how to get a quick "hello world" going to test -- `cargo run --example x` wasn't obvious.

Agreed. It isn't very that `cargo run --example` exists and when to use it/how it can be used.

>  But, yes, could be in examples/README.md. Happy to move it if you prefer ?

I personally think that information about examples should be in `examples/README.md` but I'd leave the finial decision up to the maintainers.

**Review by seanmonstar — APPROVED** [review]
Cool, thanks!

**Pull request merged**
