### PR TITLE
docs: Add example for wrap_fn()

### LINKED ISSUE #785: wrap_fn documentation/example
`wrap_fn` is only very lightly documented. I would like to use it, but it's difficult to figure out how. It would be great if the documentation or examples had a simple example of how to use it.

### PR DESCRIPTION
**Pull request by FlorianDr**
Fixes #785

### CODE REVIEW

**Review by jxs — CHANGES_REQUESTED** [review]
Hi, and thanks! 
Can you just address the `fmt` issues?

**Comment by FlorianDr** [comment]
> Hi, and thanks, LGTM!
> Can you just address the `fmt` issues?

Oh yes. Sorry, my bad.

**Comment by jxs** [comment]
Hi, sorry there are still some issues with the example it seems

**Review by jxs — APPROVED** [review]

**Comment by jxs** [comment]
thanks!

**Pull request merged**
