### PR TITLE
Add an example of a file upload service.

### PR DESCRIPTION
**Pull request by stephanbuys**
This was based on https://github.com/abonander/multipart/blob/master/examples/rocket.rs by @abonander.

### CODE REVIEW

**Comment by seanmonstar** [comment]
I opened #40 to discuss a multipart API.

**Comment by stephanbuys** [comment]
@seanmonstar should I keep this PR open, wait for filter support? Or resubmit when multipart support lands in warp proper?

**Comment by seanmonstar** [comment]
I'm not sure, to be honest. It might be useful for people to see this while support is missing? But I'd definitely rather be able to add an example using some sort of `warp::multipart::upload()` (or something) filter, since doing it the way in this example can make it pretty easy for someone to accidentally put an enormous file upload into memory...

**Comment by abonander** [comment]
Yeah that's definitely a concern.

When Warp gets a body-stream filter this example can be implemented properly, though it will need the `multipart-async` crate instead.

**Comment by stephanbuys** [comment]
Closing for now...

**Pull request closed without merging**
