### PR TITLE
impls ReplySealed for Vec<u8> and &'static [u8].

### PR DESCRIPTION
**Pull request by remexre**
what it says on the tin.

tbh, would it make sense to `impl<T: Into<hyper::Body>> ReplySealed for T`?

### CODE REVIEW

**Comment by seanmonstar** [comment]
I've figured that the `Content-Type` should probably be set automatically for `String` and `Vec<u8>` replies... What do you think of that?

**Comment by remexre** [comment]
Set automatically to what? ftr, I'm using the `&'static [u8]` with [packer](https://github.com/iptq/packer) to serve a bunch of statics; I'm setting the content-type based on file extension (since it's known to be "true" at compile time)

**Comment by seanmonstar** [comment]
I would assume that:

- `String` implies `text/plain; charset=utf-8`
- `Vec<u8>` implies `application/octet-stream`

**Comment by seanmonstar** [comment]
Looks good, though the CI failures are legit.

**Comment by remexre** [comment]
whoops, yeah, I wrote it from class :P should be good now

**Comment by seanmonstar** [comment]
Cool, thanks!

**Pull request merged**
