### PR TITLE
add warp::ws2() as a more flexible websocket filter

### PR DESCRIPTION
**Pull request by seanmonstar**
Motivated by #29 

cc @caolan

### CODE REVIEW

**Comment by scrogson** [comment]
@seanmonstar What is the rationale behind the name `Ws2` and `ws2`?

**Comment by seanmonstar** [comment]
@scrogson I'd expect them to replace the existing `ws()` filter, which returns a `Ws`. Changing them in 0.1 however is a breaking change, so I added a `2` suffix (similar to things like `futures::Stream::concat2()`). Do you think a different name is better?

**Comment by kellytk** [comment]
@seanmonstar FWIW I've seen `next` and `ng` used in identifiers to indicate what you describe.

**Comment by scrogson** [comment]
> I'd expect them to replace the existing ws() filter, which returns a Ws.

Does this mean that `ws2` and `Ws2` would become `ws` and `Ws` in `v1.0`?

> Changing them in 0.1 however is a breaking change, so I added a 2 suffix (similar to things like futures::Stream::concat2()).

In my opinion (and I could be completely wrong or mean to suggest this, but...), anything `< 1.0` is fair game for breakage. Given this is early days, I assume most people are still in the exploration phase and might not be upset about a small breaking change. I understand if you don't agree with me on that. 😉 

> Do you think a different name is better?

I guess my biggest complaint is seeing version numbers in the types rather than a module namespace.

Coming from the Erlang/Elixir world, it's not completely obvious if it's a versioning thing or the arity of the function. In Erlang the arity of a function is often used to document functions: `module:function/arity` due to the fact that functions can share the same name but take different arguments.

**Comment by seanmonstar** [comment]
> Does this mean that ws2 and Ws2 would become ws and Ws in v1.0?

Yes, though rather, in 0.2.0.

In the Rust community (and the way cargo interprets semver), it's expected that upgrading a patch version of 0.x.y to 0.x.z will continue to compile. Cargo will eagerly download the newest patch version.

> Coming from the Erlang/Elixir world, it's not completely obvious if it's a versioning thing or the arity of the function.

I've seen it far more often as "this is the newer version", with several examples in the futures crate. Though, it also happens to have a couple examples of including arity in the name, like `join3`, `join4`, etc... Yet even those are kind of lies, since it's not the actual arity (`fut.join3(one, two)`).

I've also occasionally seen `ng` (for next generation), like there was `std::vec_ng` for a while before Rust 1.0...

**Comment by caolan** [comment]
Thanks @seanmonstar, this API will do what I need.

**Comment by scrogson** [comment]
> I've seen it far more often as "this is the newer version", with several examples in the futures crate.

Good to know, thanks for taking the time to explain 👍

**Comment by jnicholls** [comment]
You could always go straight to 0.2.0 now, rather than getting people to switch to a `ws2()` and then back to `ws()` later. You can go to 0.13483024824.0, it doesn't matter. Make the API the way you want before 1.0.

**Comment by kellytk** [comment]
@jnicholls FWIW @seanmonstar described his rationale in https://github.com/seanmonstar/warp/issues/14#issuecomment-410028563 "I'll probably hold off on a breaking change for at least a little bit, so that these papercuts can be grouped up."

**Comment by jnicholls** [comment]
@kellytk Indeed, fair enough! :) Thanks.

**Pull request merged**
