### PR TITLE
Prepare v0.3.0

### PR DESCRIPTION
**Pull request by seanmonstar**

### CODE REVIEW

**Comment by aramperes** [comment]
The example in the readme will need an update as well:

https://github.com/seanmonstar/warp/blob/ffefea08050ffe8022d3391f4bd5e5ab4e95d7c9/README.md#L34-L41

**Comment by jxs** [comment]
@aramperes thanks! want to submit a PR addressing it?

**Comment by aramperes** [comment]
@jxs Looks like @alexander-jackson got it :)

**Review by jxs — COMMENTED** [review]
awesome!

**Review by jxs — APPROVED** [review]

**Comment by chunghha** [comment]
While building one of mine with  the release-0.3.0 branch, I see conflicted dependency of rand indirectly. Like as v0.7 picked by multipart v0.17.0 vs v0.8 picked by tokio-tungstenite v0.13.0  so might want to wait for https://github.com/abonander/multipart/pull/134/commits/ee033794ada7c322e3cef50713854dff873f546d merged. Otherwise I got to add rand v0.8 to the toml which is not directly used in the code of mine but to avoid the conflict and successfully compile.

**Pull request merged**
