### PR TITLE
Add From<Reject> for Rejection.

### PR DESCRIPTION
**Pull request by Koxiaet**
This allows the `?` operator to easily be used from within functions without `map_err`.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Hm, this may be a good idea, actually!

It *may* be a breaking change, though. Anyone how implemented `Reject` and `Into<Rejection>` for their own type would suddenly no longer compile with this change...

**Comment by Koxiaet** [comment]
Yes, I just checked and it is a breaking change. Save it for the next breaking update maybe?

**Comment by thomaseizinger** [comment]
What about adding a feature flag (like `unstable`) that is off by default and guards this (and other ideas which people may like but it is not totally clear if we want to commit to their API?)

**Comment by AlisCode** [comment]
Hi!

Any news on this ? This sounds like a major ergonomics improvement.

**Comment by nui** [comment]
The orphan rule that forbid this impl has been relaxed since Rust 1.41. So you can implement `From<T> for warp::Rejection` if `T` is your local type. This allows what OP asked without breaking changes.

**Review by jxs — APPROVED** [review]

**Comment by jxs** [comment]
thanks for the wait! :blue_heart:

**Pull request merged**
