### PR TITLE
Implement host filter for parsing the host from the authority (http/2) or parsing the host header (http/1.x)

### PR DESCRIPTION
**Pull request by dmeijboom**
Related: https://github.com/seanmonstar/warp/issues/432

This is the initial version of parsing the host properly in Warp. First, it tries to parse the hostname based on the `:authority` pseudo-header. If that fails it tries to parse the `Host` header for http/1.1 and http/1.

I'm aware that this is probably not the final version as it's using a `Option<String>` where in the issue there was a mention about a `Host` type. Since I'm not an expert in Rust please advice what's missing or how it could be improved.

Thanks!

### CODE REVIEW

**Comment by dmeijboom** [comment]
> Excellent first steps, thank you!
> 
> > Probably return some newtype `Host`, wrapping a `http::uri::Authority`
> 
> Would you be able to create a newtype, `pub struct Host(Authority)`, that can be returned instead of a `String`?

Yes. I added the `Host` type but I'm still struggling with handling the error properly. Does this actually work or will it silently ignore the `.map_err(|_| reject::invalid_header(name))` stuff because it's being transformed to an `Option<Host>`?

**Comment by seanmonstar** [comment]
Best way to find out is to write some tests. :D

**Comment by jakajancar** [comment]
Do I understand correctly that right now, if you want to do "virtual hosting" / support multiple domains using Warp, you're out of luck:

  - There is no way to get the authority header
  - There is no way to disable HTTP/2

?

**Comment by jakajancar** [comment]
Are all that is missing here tests, or are there other objections?
I can add them if needed.

//cc @jxs

**Comment by dmeijboom** [comment]
> Are all that is missing here tests, or are there other objections?
> I can add them if needed.
> 
> //cc @jxs

Iirc the only thing left was making sure it actually works and writing some tests. I need this as well but unfortunately haven't had the time to finish this :sweat_smile:

**Pull request closed without merging**
