### PR TITLE
Add try_bind_with_graceful_shutdown

### LINKED ISSUE #464: There is no `try_bind_with_graceful_shutdown`
We have `try_bind`, and `bind_with_graceful_shutdown`, but not the combination of the two.

### PR DESCRIPTION
**Pull request by mullr**
Fixes #464

### CODE REVIEW

**Comment by mullr** [comment]
These test failures seem to be unrelated to the change.

**Comment by ZackPierce** [comment]
I would like to use this on mainline warp, please. What would it take to move this forward?

**Comment by mullr** [comment]
Rebased on 0.2.2

**Comment by ariesdevil** [comment]
@mullr Not found in 0.2.2 release.

**Pull request merged**
