### PR TITLE
Make multipart and websocket support optional, but supported by default

### PR DESCRIPTION
**Pull request by SimonSapin**

### CODE REVIEW

**Comment by SimonSapin** [comment]
This avoids depending (through `multipart`) on old versions of `mime`, `mime_guess`, and `log` which duplicate with more recent versions that are also used. Per https://github.com/abonander/multipart/pull/121 it looks like `multipart` wants to support an old version of rustc, and so may not be open to updating its dependencies.

**Comment by seanmonstar** [comment]
I'm good with this! Thanks!

**Comment by SimonSapin** [comment]
Nice! Could you publish on crates.io?

**Comment by seanmonstar** [comment]
@SimonSapin sure! While I'm getting ready, there's nothing else that needs de-duping, right?

**Comment by SimonSapin** [comment]
I tried it with `[patch.crates-io]` on mozilla-central and I think this is it, thanks!

**Comment by seanmonstar** [comment]
Published!

**Comment by abonander** [comment]
@SimonSapin I don't care so much about old Rust support but I figured breaking on Debian-stretch might be an issue for Servo/Firefox.

**Comment by SimonSapin** [comment]
Firefox generally bumps its Rust version requirement to the latest Stable two weeks after that release: https://wiki.mozilla.org/Rust_Update_Policy_for_Firefox

**Pull request merged**
