### PR TITLE
Framework for ping-pong keep-alives

### PR DESCRIPTION
**Pull request by jq-rs**
Include full ping and pong message support for manual creation of WebSocket keep-alives as described in https://tools.ietf.org/html/rfc6455#section-5.5.2

Part of #269

### CODE REVIEW

**Comment by jq-rs** [comment]
Fails of CI seem to be non-related to changes.

**Comment by seanmonstar** [comment]
(Sorry for the slow response, been out of the office.)

I believe all of this exists in 0.2. Is there a reason to backport instead of just upgrading?

**Comment by jq-rs** [comment]
Thanks for your reply! It takes quite an effort for me to upgrade to 0.2, that is the primary reason for 0.1 PR. I am not familiar how you have planned to maintain 0.1 so decided to do a PR anyway.

Regarding 0.2 differences, I believe pong send support is missing from 0.2. I did not see quickly that is pong receive missing due to differences between 0.1 and 0.2, it was originally.

Path and query fixes are added here by mistake. Nevertheless, they fix a real crash seen on live and would be nice to have in both branches. Surprisingly http crate's `path_and_query` gets an error and expect branch is taken in Warp.

**Comment by jq-rs** [comment]
I can drop the `path_and_query` fixes, if this is wanted to be merged. If 0.1.x is not maintained anymore, then no need and this can be closed.

**Comment by seanmonstar** [comment]
I can merge and release a 0.1.x patch. To help me understand, can we separate the path_and_query piece?

**Comment by jq-rs** [comment]
Really grand if 0.1.x is supported still. I reverted the `path_and_query` changes.

**Comment by jq-rs** [comment]
Thanks for the merge! Any guidance what should I do with the `path_and_query` changes? One option is to try to do a version which does not change the API, but instead returns e.g. index-path/empty-path by default if http crate's path and query fails.

**Comment by seanmonstar** [comment]
What is the change trying to fix? I don't yet understand what the problem was :D

**Comment by jq-rs** [comment]
The problem is that `tail()` call crashes to `.expect("server URIs should always have path_and_query")`.

**Comment by seanmonstar** [comment]
Hm, I guess the only time that's not true would be `CONNECT foo.bar`...

**Comment by jq-rs** [comment]
Some bot is probably doing that to public IPs all the time.

**Pull request merged**
