### PR TITLE
Allow HEAD requests to be served by fs::dir() filter

### PR DESCRIPTION
**Pull request by zenria**
This is a fix for feature request #834

### CODE REVIEW

**Comment by joseluisq** [comment]
How about the empty body for `HEAD` responses? https://tools.ietf.org/html/rfc7231#section-4.3.2

**Comment by zenria** [comment]
The underlying HTTP server (not sure if it's hyper or tower) does not sent the body when handling HEAD requests.

This has already been done in the fs::file() filter: 

https://github.com/seanmonstar/warp/blob/4a03710adcc7acee2c773a97d25ffd3de18efea9/src/filters/fs.rs#L48-L57

**Comment by joseluisq** [comment]
Great.
Another question does the `file` need `HEAD` method support too or not?

**Comment by zenria** [comment]
I think, yes it needs it, but this is already working due to the any() filter. 

I didn't want to use the any() filter for the fs:dir() as it appears cumbersome to respond to POST or PUT requests on static files. So I think we should also disable this on the fs:file() filter and use only get+head filter

**Comment by joseluisq** [comment]
> I think, yes it needs it, but this is already working due to the any() filter.

Do you mean this is working for your addition or do you mean this `file` filter is already working that's why you don't want to break someone else code?

But yeah I'm also wondering in what cases we want to support `fs::file()` with any method.

**Comment by zenria** [comment]
> > I think, yes it needs it, but this is already working due to the any() filter.
> 
> Do you mean this is working for your addition or do you mean this `file` filter is already working that's why you don't want to break someone else code?

the second option: I did not want to break someone else code!

> 
> But yeah I'm also wondering in what cases we want to support `fs::file()` with any method.

:-)

**Review by jxs — APPROVED** [review]

**Comment by jxs** [comment]
thanks @zenria! and thanks @joseluisq for the reviewing :)

>The underlying HTTP server (not sure if it's hyper or tower) does not sent the body when handling HEAD requests.

yeah it's hyper, [see here](https://github.com/hyperium/hyper/blob/master/src/proto/h1/role.rs#L831)

**Comment by amousset** [comment]
FYI this change actually broke some code when updating from 0.3.1 to 0.3.2. We had a custom handler for HEAD but relied on `fs::dir()` for GET requests (something probably quite unusual I admit :) ). Adding a `method::get()` filter before the `fs::dir()` fixed the problem.

**Pull request merged**
