### PR TITLE
Implement Reply for Result<impl Reply, impl Reply>

### LINKED ISSUE #388: Error Handling Examples
It's possible I'm just not following the rejections example well enough, but what is the correct way of indicating that a handler (called with `and_then()`) is fallible, and returning the error from that method in a reply?

For an example of the behaviour I'm trying to replicate, in Actix or Rouille, handler functions are defined as returning something resembling a `Result<GoodReply, BadReply>`, both of which can be expected to produce an HTTP response.

e.g a simple index handler which should generate a 500 if the templating fails:
```rust
async fn index(tmpl: web::Data<tera::Tera>) -> Result<HttpResponse, Error> {
    let html = tmpl
        .render("index.html", &tera::Context::new())
        .map_err(|_| HttpResponse::InternalServerError("Failed to render template")))?;

    Ok(HttpResponse::Ok().body(html))
}
```

Reading the docs for Warp, it seems like a `Rejection` should be used to indicate that this filter could not or should not accept the request, is this the case? And if so, is there an idiomatic way to replicate the behaviour I've sketched above? I can go down the road of matching on results from fallible functions in my handlers, and doing early `return warp::reply(...)`, but then I lose out on the ergonomics offered by the `?` operator inside the function.

### PR DESCRIPTION
**Pull request by cjbassi**
This fixes the problems I've been having with error handling as described in #388. I don't think this is a breaking change since http::Error can be added to a result and you get the same effect as before. Let me know what you think of this. I also added an example demonstrating how this would be used.

Close #388

### CODE REVIEW

**Comment by cjbassi** [comment]
The one issue with this is that in the example, rejections are turned into plain text error responses instead of json but this should be easy to fix once #451 is implemented.

**Comment by cjbassi** [comment]
Actually it seems like this doesn't work with async functions since map doesn't work with async functions... :(

**Comment by jxs** [comment]
Hi, there's a PR in the pipeline to [`impl<T: Reject> From<T> for Rejection`](https://github.com/seanmonstar/warp/pull/396/) which will then allow to use the `?` operator on `Result<T: Reply, E: Reject>` will that help your case?
warp Filters are  similar to the [`futures api`](https://docs.rs/futures/0.3.1/futures), that's why `map` composes the filter with a function that maps the extracted value, while `and_then` composes the filter with a function that returns a `TryFuture` which can be an `async fn` that returns `Result<impl Reply, Rejection>`

**Comment by cjbassi** [comment]
I hadn't seen that pull request but it turns out that I implemented the same thing in my codebase and unfortunately it did not do the trick for me since I still had to add a whole bunch of `.map_error(MyError::from)` to convert external errors to my error type first before using `?` which was pretty unergonomic.

Yah, I ended up studying the Futures API quite a bit yesterday to see if there was a way to do an async map with the current API :) But it doesn't look possible so I had to add a new method.

**Comment by cjbassi** [comment]
Another idea: what if instead of having to return a Rejection struct we returned the Reject trait? That might work instead. So return values would be Result<impl Reply, impl Reject>. The Reject trait would probably have to be reworked. Idk if that would work, just throwing stuff out there.

**Comment by sidju** [comment]
I am very interested in this.

Implementing Reply for Result where both implement reply seems trivial and a reasonable thing to add in general. When also combined with some kind of async .map it would suddenly enable me to write handlers as I would like, since handlers should infallibly return a response when executed and should fail fast on errors.

Of all the solutions mentioned in [https://github.com/seanmonstar/warp/issues/388](https://github.com/seanmonstar/warp/issues/388) this one seems the best.

(It seems to me that the clash with the futures API here lies in the fact that warp has declared the error type for us and given it special meaning.

It works great in the context of routing and makes writing your own filters a breeze, but it also requires the user to interact with this error type even when it is irrelevant.

This causes frustration when the ? operator could normally be used but the error type is strictly set by warp (and not recommended for returning from a handler, since it was the right route). 

Due to this (and the odd nature of request handlers compared to other "normal" async operations) I would say there is a need for a .map_async or .handler)

**Review by kaj — APPROVED** [review]
This looks good!  The changes in `src/reply.rs` is pretty much identical to a PR i did before seeing this (and closed as duplicate on finding this).  I'm not familiar enough with warp internals to say if the contents of `filter/map_sync.rs` are correct, but i _am_ familiar enough with _using_ warp to say that the `FilterBase::map_async` function is dearly wanted.

Of course, sitting since February there is merge conflicts to resolve, and the `map_async` function does need documentation.  Is @cjbassi still around and interested on doing that?  Or should I clone the branch, do the rebase and doc and submit a new PR?

**Comment by PPakalns** [comment]
Resolved merge conflicts with the current master branch for this PR in [PPakalns/warp](https://github.com/PPakalns/warp) as I needed an up to date version. Can be used as a reference to fix conflicts in this PR or to make a new PR.

**Comment by jxs** [comment]
superseeded by #878

**Comment by sidju** [comment]
On the contrary, #878 doesn't implement Reply for Result<Reply, Reply>. Whilst the .map_async is indeed covered the Reply implementation may still be of relevance.

**Pull request closed without merging**
