### PR TITLE
Update tungstenite to 0.17.2

### PR DESCRIPTION
**Pull request by emixa-d**
The build system I use (antioxidant) hasn't implemented tests yet
and uses a different dependency resolving system,
so best double-check.

### CODE REVIEW

**Comment by emixa-d** [comment]
Oops is bogus

**Comment by emixa-d** [comment]
Now corrected (at least, it builds)

**Review by jxs — APPROVED** [review]

**Comment by emixa-d** [comment]
(Also, I know very little about websocket, warp and tungstenite)

**Comment by jxs** [comment]
thanks!

**Pull request merged**
